---
parameters:
  image: <Image ID>
  key_name: <Key Name>
  root_password: <Password>
  admin_flavor: m1.large
  master_flavor: m1.large
  worker_flavor: m1.large
  worker_count: 3
  external_net: <External Network Name or ID>
  internal_net_cidr: <Internal Network Range>
  dns_nameserver: <DNS Nameserver for CaaSP>
